tobysangster/rails_airbnb_clone

app/models/booking.rb
app/models/equipment.rb
db/migrate/20201116164058_create_equipment.rb
db/migrate/20201116164515_create_bookings.rb
test/models/booking_test.rb
test/models/equipment_test.rb

Hey guys, we are having so much fun, either you send me 5 bitcoins or you accept my commit!

models created

---

app/controllers/equipment_controller.rb
app/views/equipment/index.html.erb
config/routes.rb
test/controllers/equipment_controller_test.rb

Love you guys and girls! Please accept changes!

Controllers

---

app/controllers/bookings_controller.rb
app/controllers/equipment_controller.rb
config/routes.rb
test/controllers/bookings_controller_test.rb

I added some very nice features let's have a look!

bookings controller created

---

app/models/booking.rb
app/models/equipment.rb
app/models/user.rb
db/migrate/20201117144845_rename_totl_price_to_total_price_in_bookings.rb
db/schema.rb

Hey guys I added the validations and change a syntax error in the bookings table

adding validation

---

Gemfile
Gemfile.lock
db/seeds.rb

Please check if you agree with the seeds I just added

Some seeds has been added

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/equipment/index.html.erb

equipment card almost finished. Please accept!

equipment cards almost done

---

app/controllers/bookings_controller.rb
app/models/booking.rb
app/views/bookings/new.html.erb
app/views/equipment/show.html.erb
app/views/pages/home.html.erb

Do you want to have a look to our bookings system that we added? we only need a page to display all the bookings

added links and bookings

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

Navbar menu

---

app/views/equipment/show.html.erb
app/views/shared/_navbar.html.erb

The logo is now linked to the homepage and we have a button to go back from the equipment show page to the index show page

adding new features

---

app/assets/stylesheets/components/_spacer.scss
app/views/bookings/new.html.erb
app/views/equipment/index.html.erb
app/views/equipment/new.html.erb
app/views/equipment/show.html.erb
app/views/pages/dashboard.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

I added some margin-top at the beginning of each page because the navbar was hidding the info on the top of each pages

added margin-top on all pages

---

app/controllers/equipment_controller.rb
app/controllers/pages_controller.rb
app/models/user.rb
app/views/equipment/edit.html.erb
app/views/equipment/index.html.erb
app/views/equipment/show.html.erb
app/views/pages/dashboard.html.erb

Added some new features to the dashboard

building-out-dashboard

---

app/assets/stylesheets/components/_card.scss
app/controllers/equipment_controller.rb
app/models/equipment.rb
app/views/equipment/edit.html.erb
app/views/equipment/new.html.erb
app/views/shared/_navbar.html.erb
db/migrate/20201119124731_add_location_to_equipment.rb
db/schema.rb

location added to equipment table and form

location added to equipment table and form

---

app/views/equipment/show.html.erb

You can now see the edit and delete button just if you are the same user that posted the item

new features added

---

app/assets/stylesheets/components/_card.scss
app/views/equipment/index.html.erb

card with random review numbers

cards with reviews

---

app/controllers/bookings_controller.rb
app/views/bookings/edit.html.erb
app/views/pages/dashboard.html.erb
config/routes.rb

You can now edit and delete your bookings

add delete and edit buttons

---

app/models/equipment.rb
app/models/user.rb
app/views/pages/dashboard.html.erb

You can see if you have listed equipment booked

new-booking-features

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_show.scss
app/views/equipment/show.html.erb

latest equipment css work in progress

equipment show page still in progress

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_show.scss

ewuipment show page nearly finished

equipment show page

---

Gemfile
Gemfile.lock
app/controllers/equipment_controller.rb
app/models/equipment.rb
app/views/pages/home.html.erb

New branch

---

app/javascript/packs/application.js
app/views/pages/dashboard.html.erb
config/routes.rb

dashboard buttons finished, links working.

dashboard buttons finished

---

Gemfile
Gemfile.lock
app/controllers/equipment_controller.rb
app/models/equipment.rb
app/views/pages/home.html.erb

Reverts tobysangster/rails_airbnb_clone#66

Revert "New branch"

---

Gemfile
Gemfile.lock
app/controllers/equipment_controller.rb
app/models/equipment.rb
app/views/pages/home.html.erb

Reverts tobysangster/rails_airbnb_clone#67

Revert "Revert "New branch""

---

app/views/equipment/show.html.erb

back button leads to previous page

back button

---

app/views/shared/_navbar.html.erb

dropdown menu right

---

app/views/pages/dashboard.html.erb

overflow on dashboard completed

overflow dashboard
